service: azure-terraform-cost-estimator
frameworkVersion: '2'
provider:
  name: aws
  runtime: go1.x
  tracing:
    apiGateway: true
    lambda: true

# you can overwrite defaults here
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-2'}
  timeout: 600

  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource: "*"

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  api:
    handler: bin/api
    events:
      - http:
          path: estimate
          method: post

resources: