name: Main Branch Build
on:
  push:
    branches:
      - main
jobs:
  deploy-dev:
    name: Deploy Dev Environment
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13.x
    - name: Build Functions
      run: make build
    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy --verbose --stage dev --region us-east-2
  intg-test:
    name: Integration Testing
    runs-on: ubuntu-latest
    needs: deploy-dev
    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13.x
      - name: az login
        run: az login --service-principal --username ${{ secrets.ARM_CLIENT_ID }} --password ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}
      - name: Integration Tests
        run:  go test -v ./test/integration_test.go
  deploy-prod:
    name: Deploy Prod Environment
    runs-on: ubuntu-latest
    needs: intg-test
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13.x
      - name: Build Functions
        run: make build
      - name: serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy --verbose --stage prod --region us-east-2